class AllahName {
  final String nameAr;
  final String nameEn;
  final String meaningEn;
  final String nameBn;
  final String meaningBn;

  AllahName({
    required this.nameAr,
    required this.nameEn,
    required this.meaningEn,
    required this.nameBn,
    required this.meaningBn,
  });
}

class AllahNames {
  static final List<AllahName> names = [
    AllahName(
        nameAr: "الرحمن",
        nameEn: "Ar-Rahman",
        meaningEn: "The All-Compassionate",
        nameBn: "আর রাহমান",
        meaningBn: "পরম দয়ালু"),
    AllahName(
        nameAr: "الرحيم",
        nameEn: "Ar-Rahim",
        meaningEn: "The All-Merciful",
        nameBn: "আর রহিম",
        meaningBn: "অতিশয় মেহেরবান"),
    AllahName(
        nameAr: "الملك",
        nameEn: "Al-Malik",
        meaningEn: "The Absolute Ruler",
        nameBn: "আল মালিক",
        meaningBn: "সর্বকর্তৃত্বময়"),
    AllahName(
        nameAr: "القدوس",
        nameEn: "Al-Quddus",
        meaningEn: "The Pure One",
        nameBn: "আল কুদ্দুস",
        meaningBn: "অতি পবিত্র"),
    AllahName(
        nameAr: "السلام",
        nameEn: "As-Salam",
        meaningEn: "The Source of Peace",
        nameBn: "আস সালাম",
        meaningBn: "শান্তি দানকারী"),
    AllahName(
        nameAr: "المؤمن",
        nameEn: "Al-Mu’min",
        meaningEn: "The Inspirer of Faith",
        nameBn: "আল মুমিন",
        meaningBn: "নিরাপত্তা ও ঈমান দানকারী"),
    AllahName(
        nameAr: "المهيمن",
        nameEn: "Al-Muhaymin",
        meaningEn: "The Guardian",
        nameBn: "আল মুহাইমিন",
        meaningBn: "পরিপূর্ণ রক্ষণাবেক্ষণকারী"),
    AllahName(
        nameAr: "العزيز",
        nameEn: "Al-Aziz",
        meaningEn: "The Victorious",
        nameBn: "আল আজিজ",
        meaningBn: "পরাক্রমশালী"),
    AllahName(
        nameAr: "الجبار",
        nameEn: "Al-Jabbar",
        meaningEn: "The Compeller",
        nameBn: "আল জাব্বার",
        meaningBn: "দুর্নিবার"),
    AllahName(
        nameAr: "المتكبر",
        nameEn: "Al-Mutakabbir",
        meaningEn: "The Greatest",
        nameBn: "আল মুতাকাব্বির",
        meaningBn: "নিরঙ্কুশ শ্রেষ্ঠত্বের অধিকারী"),
    AllahName(
        nameAr: "الخالق",
        nameEn: "Al-Khaliq",
        meaningEn: "The Creator",
        nameBn: "আল খালিক",
        meaningBn: "সৃষ্টিকর্তা"),
    AllahName(
        nameAr: "البارئ",
        nameEn: "Al-Bari’",
        meaningEn: "The Maker of Order",
        nameBn: "আল বারী",
        meaningBn: "সঠিকভাবে সৃষ্টিকারী"),
    AllahName(
        nameAr: "المصور",
        nameEn: "Al-Musawwir",
        meaningEn: "The Shaper of Beauty",
        nameBn: "আল মুসাউইর",
        meaningBn: "আকৃতি দানকারী"),
    AllahName(
        nameAr: "الغفار",
        nameEn: "Al-Ghaffar",
        meaningEn: "The Forgiving",
        nameBn: "আল গাফ্ফার",
        meaningBn: "পরম ক্ষমাশীল"),
    AllahName(
        nameAr: "القهار",
        nameEn: "Al-Qahhar",
        meaningEn: "The Subduer",
        nameBn: "আল ক্বাহার",
        meaningBn: "কঠোর"),
    AllahName(
        nameAr: "الوهاب",
        nameEn: "Al-Wahhab",
        meaningEn: "The Giver of All",
        nameBn: "আল ওয়াহ্হাব",
        meaningBn: "সবকিছু দানকারী"),
    AllahName(
        nameAr: "الرزاق",
        nameEn: "Ar-Razzaq",
        meaningEn: "The Sustainer",
        nameBn: "আর রাজ্জাক",
        meaningBn: "রিযিকদাতা"),
    AllahName(
        nameAr: "الفتاح",
        nameEn: "Al-Fattah",
        meaningEn: "The Opener",
        nameBn: "আল ফাত্তাহ",
        meaningBn: "বিজয়দানকারী"),
    AllahName(
        nameAr: "العليم",
        nameEn: "Al-'Alim",
        meaningEn: "The Knower of All",
        nameBn: "আল আলীম",
        meaningBn: "সর্বজ্ঞ"),
    AllahName(
        nameAr: "القابض",
        nameEn: "Al-Qabid",
        meaningEn: "The Constrictor",
        nameBn: "আল কাবিদ্ব",
        meaningBn: "সংকীর্ণকারী"),
    AllahName(
        nameAr: "الباسط",
        nameEn: "Al-Basit",
        meaningEn: "The Reliever",
        nameBn: "আল বাসিত",
        meaningBn: "প্রশস্তকারী"),
    AllahName(
        nameAr: "الخافض",
        nameEn: "Al-Khafid",
        meaningEn: "The Abaser",
        nameBn: "আল খাফিদ",
        meaningBn: "অবনতকারী"),
    AllahName(
        nameAr: "الرافع",
        nameEn: "Ar-Rafi",
        meaningEn: "The Exalter",
        nameBn: "আর রাফী",
        meaningBn: "উন্নতকারী"),
    AllahName(
        nameAr: "المعز",
        nameEn: "Al-Mu’izz",
        meaningEn: "The Bestower of Honors",
        nameBn: "আল মুজিব",
        meaningBn: "সম্মান দানকারী"),
    AllahName(
        nameAr: "المذل",
        nameEn: "Al-Mudhill",
        meaningEn: "The Humiliator",
        nameBn: "আল মুদ্বিল্ল",
        meaningBn: "(অবিশ্বাসীদের) বেইজ্জতকারী"),
    AllahName(
        nameAr: "السميع",
        nameEn: "As-Sami",
        meaningEn: "The Hearer of All",
        nameBn: "আস সামি",
        meaningBn: "সর্বশ্রোতা"),
    AllahName(
        nameAr: "البصير",
        nameEn: "Al-Basir",
        meaningEn: "The Seer of All",
        nameBn: "আল বাসীর",
        meaningBn: "সর্ববিষয় দর্শনকারী"),
    AllahName(
        nameAr: "الحكم",
        nameEn: "Al-Hakam",
        meaningEn: "The Judge",
        nameBn: "আল হাকাম",
        meaningBn: "অতল বিচারক"),
    AllahName(
        nameAr: "العدل",
        nameEn: "Al-'Adl",
        meaningEn: "The Just",
        nameBn: "আল আদল",
        meaningBn: "পরিপূর্ণ ন্যায়বিচারক"),
    AllahName(
        nameAr: "اللطيف",
        nameEn: "Al-Latif",
        meaningEn: "The Subtle One",
        nameBn: "আল লতিফ",
        meaningBn: "সকল গোপন বিষয়ে অবগত"),
    AllahName(
        nameAr: "الخبير",
        nameEn: "Al-Khabir",
        meaningEn: "The All-Aware",
        nameBn: "আল খাবির",
        meaningBn: "সকল বিষয়ে জ্ঞাত"),
    AllahName(
        nameAr: "الحليم",
        nameEn: "Al-Halim",
        meaningEn: "The Forbearing",
        nameBn: "আল হালিম",
        meaningBn: "অত্যন্ত ধর্য্যশীল"),
    AllahName(
        nameAr: "العظيم",
        nameEn: "Al-Azim",
        meaningEn: "The Magnificent",
        nameBn: "আল আজিম",
        meaningBn: "সর্বত্ত মর্যাদাশীল"),
    AllahName(
        nameAr: "الغفور",
        nameEn: "Al-Ghafur",
        meaningEn: "The Forgiver and Hider of Faults",
        nameBn: "আল গফুর",
        meaningBn: "পরম ক্ষমাশীল"),
    AllahName(
        nameAr: "الشكور",
        nameEn: "Ash-Shakur",
        meaningEn: "The Rewarder of Thankfulness",
        nameBn: "আস শাকুর",
        meaningBn: "গুন্গ্রাহী"),
    AllahName(
        nameAr: "العلى",
        nameEn: "Al-Ali",
        meaningEn: "The Highest",
        nameBn: "আল আলী",
        meaningBn: "উচ্চ মর্যাদাশীল"),
    AllahName(
        nameAr: "الكبير",
        nameEn: "Al-Kabir",
        meaningEn: "The Greatest",
        nameBn: "আল কাবিইর",
        meaningBn: "সুমহান"),
    AllahName(
        nameAr: "الحفيظ",
        nameEn: "Al-Hafiz",
        meaningEn: "The Preserver",
        nameBn: "আল হাফীজ",
        meaningBn: "সংরক্ষণকারী"),
    AllahName(
        nameAr: "المقيت",
        nameEn: "Al-Muqit",
        meaningEn: "The Nourisher",
        nameBn: "আল মুক্বিত",
        meaningBn: "সকলের জীবনোপকরণ দানকারী"),
    AllahName(
        nameAr: "الحسيب",
        nameEn: "Al-Hasib",
        meaningEn: "The Accounter",
        nameBn: "আল হাসিব",
        meaningBn: "হিসাব গ্রহণকারী"),
    AllahName(
        nameAr: "الجليل",
        nameEn: "Al-Jalil",
        meaningEn: "The Mighty",
        nameBn: "আল জলীল",
        meaningBn: "পরম মর্যাদার অধিকারী"),
    AllahName(
        nameAr: "الكريم",
        nameEn: "Al-Karim",
        meaningEn: "The Generous",
        nameBn: "আল কারীম",
        meaningBn: "সুমহান দাতা"),
    AllahName(
        nameAr: "الرقيب",
        nameEn: "Ar-Raqib",
        meaningEn: "The Watchful One",
        nameBn: "আল রাক্বীব",
        meaningBn: "তত্ত্বাবধায়ক"),
    AllahName(
        nameAr: "المجيب",
        nameEn: "Al-Mujib",
        meaningEn: "The Responder to Prayer",
        nameBn: "আল মুজীব",
        meaningBn: "কবুলকারী"),
    AllahName(
        nameAr: "الواسع",
        nameEn: "Al-Wasi",
        meaningEn: "The All-Comprehending",
        nameBn: "আল ওয়াসি",
        meaningBn: "সর্বত্ত বিরাজমান"),
    AllahName(
        nameAr: "الحكيم",
        nameEn: "Al-Hakim",
        meaningEn: "The Perfectly Wise",
        nameBn: "আল হাকীম",
        meaningBn: "পরম প্রজ্ঞাময়"),
    AllahName(
        nameAr: "الودود",
        nameEn: "Al-Wadud",
        meaningEn: "The Loving One",
        nameBn: "আল ওয়াদুদ",
        meaningBn: "(বান্দাদের প্রতি) সদয়"),
    AllahName(
        nameAr: "المجيد",
        nameEn: "Al-Majeed",
        meaningEn: "The Majestic One",
        nameBn: "আল মাজীদ",
        meaningBn: "সকল মর্যাদার অধিকারী"),
    AllahName(
        nameAr: "الباعث",
        nameEn: "Al-Ba’ith",
        meaningEn: "The Resurrector",
        nameBn: "আল বাইস",
        meaningBn: "পুনরুজ্জীবিতকারী"),
    AllahName(
        nameAr: "الشهيد",
        nameEn: "Ash-Shahid",
        meaningEn: "The Witness",
        nameBn: "আশ শাহীদ",
        meaningBn: "সর্বজ্ঞ স্বাক্ষী"),
    AllahName(
        nameAr: "الحق",
        nameEn: "Al-Haqq",
        meaningEn: "The Truth",
        nameBn: "আল হাক্ব",
        meaningBn: "পরম সত্য"),
    AllahName(
        nameAr: "الوكيل",
        nameEn: "Al-Wakil",
        meaningEn: "The Trustee",
        nameBn: "আল ওয়াকিল",
        meaningBn: "পরম নির্ভরযোগ্য কর্ম-সম্পাদনকারী"),
    AllahName(
        nameAr: "القوى",
        nameEn: "Al-Qawiyy",
        meaningEn: "The Possessor of All Strength",
        nameBn: "আল ক্বাউইউ",
        meaningBn: "পরম শক্তির অধিকারী"),
    AllahName(
        nameAr: "المتين",
        nameEn: "Al-Matin",
        meaningEn: "The Forceful One",
        nameBn: "আল মাতীন",
        meaningBn: "সুদৃঢ়"),
    AllahName(
        nameAr: "الولى",
        nameEn: "Al-Waliyy",
        meaningEn: "The Governor",
        nameBn: "আল ওয়ালীইউ",
        meaningBn: "অভিভাবক ও সাহায্যকারী"),
    AllahName(
        nameAr: "الحميد",
        nameEn: "Al-Hamid",
        meaningEn: "The Praised One",
        nameBn: "আল হামীদ",
        meaningBn: "সকল প্রশংসার অধিকারী"),
    AllahName(
        nameAr: "المحصى",
        nameEn: "Al-Muhsi",
        meaningEn: "The Appraiser",
        nameBn: "আল মুহসি",
        meaningBn: "সকল সৃষ্টির ব্যাপারে অবগত"),
    AllahName(
        nameAr: "المبدئ",
        nameEn: "Al-Mubdi’",
        meaningEn: "The Originator",
        nameBn: "আল মুব্দি",
        meaningBn: "প্রথমবার সৃষ্টিকর্তা"),
    AllahName(
        nameAr: "المعيد",
        nameEn: "Al-Mu’id",
        meaningEn: "The Restorer",
        nameBn: "আল মুঈদ",
        meaningBn: "পুনরায় সৃষ্টিকর্তা"),
    AllahName(
        nameAr: "المحيى",
        nameEn: "Al-Muhyi",
        meaningEn: "The Giver of Life",
        nameBn: "আল মুহয়ি",
        meaningBn: "জীবন দানকারী"),
    AllahName(
        nameAr: "المميت",
        nameEn: "Al-Mumit",
        meaningEn: "The Taker of Life",
        nameBn: "আল মুমীত",
        meaningBn: "মৃত্যু দানকারী"),
    AllahName(
        nameAr: "الحي",
        nameEn: "Al-Hayy",
        meaningEn: "The Ever-Living One",
        nameBn: "আল হাইয়্যু",
        meaningBn: "চিরঞ্জীব"),
    AllahName(
        nameAr: "القيوم",
        nameEn: "Al-Qayyum",
        meaningEn: "The Self-Existing One",
        nameBn: "আল ক্বাইয়ূম",
        meaningBn: "সমস্ত কিছুর ধারক ও সংরক্ষণকারী"),
    AllahName(
        nameAr: "الواجد",
        nameEn: "Al-Wajid",
        meaningEn: "The Finder",
        nameBn: "আল ওয়াজীদ",
        meaningBn: "অফুরন্ত ভান্ডারের অধিকারী"),
    AllahName(
        nameAr: "الماجد",
        nameEn: "Al-Majid",
        meaningEn: "The Glorious",
        nameBn: "আল মাজীদ",
        meaningBn: "শ্রেষ্ঠত্বের অধিকারী"),
    AllahName(
        nameAr: "الواحد",
        nameEn: "Al-Wahid",
        meaningEn: "The Unique, The Single",
        nameBn: "আল ওয়া’হিদ",
        meaningBn: "এক ও অদ্বিতীয়"),
    AllahName(
        nameAr: "الاحد",
        nameEn: "Al-Ahad",
        meaningEn: " The One, The Indivisible",
        nameBn: "আল আহাদ",
        meaningBn: "এক"),
    AllahName(
        nameAr: "الصمد",
        nameEn: "As-Samad",
        meaningEn: "The Satisfier of All Needs",
        nameBn: "আস সামাদ",
        meaningBn: "অমুখাপেক্ষি"),
    AllahName(
        nameAr: "القادر",
        nameEn: "Al-Qadir",
        meaningEn: "The All-Powerful",
        nameBn: "আল ক্বাদীর",
        meaningBn: "সর্বশক্তিমান"),
    AllahName(
        nameAr: "المقتدر",
        nameEn: "Al-Muqtadir",
        meaningEn: "The Creator of All Power",
        nameBn: "আল মুক্তাদির",
        meaningBn: "নিরঙ্কুশ সিদ্ধান্তের অধিকারী"),
    AllahName(
        nameAr: "المقدم",
        nameEn: "Al-Muqaddim",
        meaningEn: "The Expediter",
        nameBn: "আল মুক্বদ্দিম",
        meaningBn: "অগ্রসারক"),
    AllahName(
        nameAr: "المؤخر",
        nameEn: "Al-Mu’akhkhir",
        meaningEn: "The Delayer",
        nameBn: "আল মুয়াক্ষীর",
        meaningBn: "অবকাশ দানকারী"),
    AllahName(
        nameAr: "الأول",
        nameEn: "Al-Awwal",
        meaningEn: "The First",
        nameBn: "আল আউয়াল",
        meaningBn: "অনাদি"),
    AllahName(
        nameAr: "الأخر",
        nameEn: "Al-Akhir",
        meaningEn: "The Last",
        nameBn: "আল আখির",
        meaningBn: "অনন্ত, সর্বশেষ"),
    AllahName(
        nameAr: "الظاهر",
        nameEn: "Az-Zahir",
        meaningEn: "The Manifest One",
        nameBn: "আল জাহির",
        meaningBn: "সম্পূর্ণরূপে প্রকাশিত"),
    AllahName(
        nameAr: "الباطن",
        nameEn: "Al-Batin",
        meaningEn: "The Hidden One",
        nameBn: "আল বাত্বিন",
        meaningBn: "দৃষ্টি হতে অদৃশ্য"),
    AllahName(
        nameAr: "الوالي",
        nameEn: "Al-Wali",
        meaningEn: "The Protecting Friend",
        nameBn: "আল ওয়ালী",
        meaningBn: "সমস্ত কিছুর অভিভাবক"),
    AllahName(
        nameAr: "المتعالي",
        nameEn: "Al-Muta’ali",
        meaningEn: "The Supreme One",
        nameBn: "আল মুতা’আলী",
        meaningBn: "সৃষ্টির গুণাবলীর উর্দ্ধে"),
    AllahName(
        nameAr: "البر",
        nameEn: "Al-Barr",
        meaningEn: "The Doer of Good",
        nameBn: "আল বার্",
        meaningBn: "পরম উপকারী"),
    AllahName(
        nameAr: "التواب",
        nameEn: "At-Tawwab",
        meaningEn: "The Guide to Repentance",
        nameBn: "আত তাওয়াব",
        meaningBn: "তাওবার তৌফিক দানকারী ও কবুলকারী"),
    AllahName(
        nameAr: "المنتقم",
        nameEn: "Al-Muntaqim",
        meaningEn: "The Avenger",
        nameBn: "আল মুনতাক্বীম",
        meaningBn: "প্রতিশোধ গ্রহণকারী"),
    AllahName(
        nameAr: "العفو",
        nameEn: "Al-‘Afuww",
        meaningEn: "The Forgiver",
        nameBn: "আল আফঊ",
        meaningBn: "পরম উদার"),
    AllahName(
        nameAr: "الرؤوف",
        nameEn: "Ar-Ra’uf",
        meaningEn: "The Clement",
        nameBn: "আর রউফ",
        meaningBn: "পরম স্নেহশীল"),
    AllahName(
        nameAr: "مالك الملك",
        nameEn: "Malik-al-Mulk",
        meaningEn: "The Owner of All",
        nameBn: "মালিকুল মূলক",
        meaningBn: "সমগ্র জগতের বাদশাহ"),
    AllahName(
        nameAr: "ذو الجلال و الإكرام",
        nameEn: "Dhu-al-Jalal wa-al-Ikram",
        meaningEn: "The Lord of Majesty and Bounty",
        nameBn: "যুল জালালী ওয়াল ইকরাম",
        meaningBn: "মহিমান্বিত ও দয়াবান সত্তা"),
    AllahName(
        nameAr: "المقسط",
        nameEn: "Al-Muqsit",
        meaningEn: "The Equitable One",
        nameBn: "আল মুক্বসিত",
        meaningBn: "হকদারের হোক আদায়কারী"),
    AllahName(
        nameAr: "الجامع",
        nameEn: "Al-Jami’",
        meaningEn: "The Gatherer",
        nameBn: "আল জামিই",
        meaningBn: "একত্রকারী, সমবেতকারী"),
    AllahName(
        nameAr: "الغنى",
        nameEn: "Al-Ghani",
        meaningEn: "The Rich One",
        nameBn: "আল গানি",
        meaningBn: "অমুখাপেক্ষি ধনী"),
    AllahName(
        nameAr: "المغنى",
        nameEn: "Al-Mughni",
        meaningEn: "The Enricher",
        nameBn: "আল মুগনিই",
        meaningBn: "পরম অভাবমোচনকারী"),
    AllahName(
        nameAr: "المانع",
        nameEn: "Al-Mani'",
        meaningEn: "The Preventer of Harm",
        nameBn: "আল মানিই",
        meaningBn: "অকল্যাণরোধক"),
    AllahName(
        nameAr: "الضار",
        nameEn: "Ad-Darr",
        meaningEn: "The Creator of The Harmful",
        nameBn: "আয্ যর",
        meaningBn: "ক্ষতিসাধনকারী"),
    AllahName(
        nameAr: "النافع",
        nameEn: "An-Nafi’",
        meaningEn: "The Creator of Good",
        nameBn: "আন নাফিই’",
        meaningBn: "কল্যাণকারী"),
    AllahName(
        nameAr: "النور",
        nameEn: "An-Nur",
        meaningEn: "The Light",
        nameBn: "আন নূর",
        meaningBn: "পরম আলো"),
    AllahName(
        nameAr: "الهادي",
        nameEn: "Al-Hadi",
        meaningEn: "The Guide",
        nameBn: "আল হাদী",
        meaningBn: "পথ প্রদর্শক"),
    AllahName(
        nameAr: "البديع",
        nameEn: "Al-Badi",
        meaningEn: "The Originator",
        nameBn: "আল বাদীই",
        meaningBn: "অতুলনীয়"),
    AllahName(
        nameAr: "الباقي",
        nameEn: "Al-Baqi",
        meaningEn: "The Everlasting One",
        nameBn: "আল বাক্বী",
        meaningBn: "চিরস্থায়ী, অবিনশ্বর"),
    AllahName(
        nameAr: "الوارث",
        nameEn: "Al-Warith",
        meaningEn: "The Inheritor of All",
        nameBn: "আল ওয়ারিস",
        meaningBn: "উত্তরাধিকারী"),
    AllahName(
        nameAr: "الرشيد",
        nameEn: "Ar-Rashid",
        meaningEn: "The Righteous Teacher",
        nameBn: "আর রাশীদ",
        meaningBn: "সঠিক পথ প্রদর্শক"),
    AllahName(
        nameAr: "الصبور",
        nameEn: "As-Sabur",
        meaningEn: "The Patient One",
        nameBn: "আস সাবুর",
        meaningBn: "অত্যাধিক ধর্য্য ধারণকারী"),
  ];
}
